import Header from "@/components/Header";
import PromptInput from "@/components/PromptInput";
import "../styles/global.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    showPromptInput = true,
}: {
    children: React.ReactNode;
    showPromptInput?: boolean;
}) {
    return (
        <html lang="en">
            <body>
                <Header />
                {showPromptInput && <PromptInput />}
                {children}
            </body>
        </html>
    );
}
